### PR TITLE
Fix crashes in AsmMethodSource(#1577,#1580)

### PR DESCRIPTION
**Pull request by FXTi**
Fix: https://github.com/soot-oss/soot/issues/1577

* `mergeIn()` should resolve the right `stack_n := @caughtException` when `nop` for `InlineExceptionHandler` appears.
* `UnitContainer` may appear instead of `nop` for `InlineExceptionHandler`.

Fix: https://github.com/soot-oss/soot/issues/1580

* Replace `Edge.stack` with `Edge.stacks` and keep `stack`s in the same order as `edge`s in `worklist`.

### CODE REVIEW

**Comment by linghuiluo** [comment]
This fix doesn't look so trivial. Can you provide unit tests?

**Comment by FXTi** [comment]
No, but I recommend add some unit tests for this pr.

**Comment by linghuiluo** [comment]
@FXTi Will you add the tests? If you add the tests, I can review this PR.

**Comment by linghuiluo** [comment]
@swissiety Can you add the two test cases into soot and see if the bugs are still there? If it is the case, make a pull request with the tests and mark them as ignored at first.

**Pull request closed without merging**
