### PR TITLE
Fix for #1562

### PR DESCRIPTION
**Pull request by piskachev**
If the option ignore-resolution-errors is enabled Soot should not fail when super class does not exist. This can happen when some library generates classes that land in the Scene as non phantom. Hence, it can happen that some of them have incomplete hierarchy (Soot throws exception when super class is not found). 
This is fix for ticket #1562

### CODE REVIEW

**Comment by mbenz89** [comment]
@piskachev look fine to me! Have you tested if allowing `null` as superclass does not lead to errors elsewhere?

**Comment by piskachev** [comment]
> @piskachev look fine to me! Have you tested if allowing `null` as superclass does not lead to errors elsewhere?

yes, tested! To make sure it does not fails, should I add the same condition (&& !Options.v().ignore_resolution_errors()) also in BytecodeHierarchy:75 ?

**Comment by mbenz89** [comment]
>yes, tested! To make sure it does not fails, should I add the same condition (&& !Options.v().ignore_resolution_errors()) also in BytecodeHierarchy:75 ?

Yes. That would be good. Thereby, we at least do not break any assumption when having `!Options.v().ignore_resolution_errors()`

**Comment by piskachev** [comment]
I added the change.

**Review by ericbodden — COMMENTED** [review]
Looks good to me. Thanks!

**Pull request merged**
