### PR TITLE
Add Conditional Constant Propagator and Folder

### PR DESCRIPTION
**Pull request by FXTi**
Implementation of Conditional Constant Propagation from the paper of Wegman and Zadeck "Constant Propagation with Conditional Branches".
[PDF Link](https://www.cs.utexas.edu/users/lin/cs380c/wegman.pdf.)

Please review this and give some advice, thanks!

### CODE REVIEW

**Comment by FXTi** [comment]
ping. @mbenz89 @anddann

**Comment by anddann** [comment]
Thx for your contribution!
Before going through your code, can you please make the pipeline succeding or do you need help here?

**Comment by FXTi** [comment]
> Thx for your contribution!
> Before going through your code, can you please make the pipeline succeding or do you need help here?

Done.

**Comment by anddann** [comment]
Thanks a lot... I'll go through the code.. please give me some time

**Comment by FXTi** [comment]
> Thanks a lot... I'll go through the code.. please give me some time
> is there a reason that you want it to be merge into `master` but not into `develop`

No, already changed

**Pull request closed without merging**
