### PR TITLE
Run NopEliminator at the end of baf body creation/processing 

### PR DESCRIPTION
**Pull request by tim-hoffman**

### CODE REVIEW

**Comment by linghuiluo** [comment]
@tim-hoffman  Can you explain why we need this?

**Comment by linghuiluo** [comment]
@tim-hoffman also other PRs you made, a description of the PR and some tests will be appreciated. Can you add them? We will be happy to review your PRs if you add them.

**Comment by tim-hoffman** [comment]
When running Soot on classes in Oracle JDK 8 standard libraries, I ran into a few cases where the generated bytecode was larger than the allowed limit of 64K bytes. However, it contained many 'nop' statements remaining from the Jimple-to-Baf translation. There is no harm in removing 'nop' statements from the Baf code and doing so did allow the methods I was analyzing to fit within the 64K limit.

**Comment by linghuiluo** [comment]
@tim-hoffman thanks for explaining the purpose, it makes sense. For such cases, maybe you could just split the class into multiple files?

**Comment by linghuiluo** [comment]
@tim-hoffman  I saw you have merged many of your pull requests directly into the develop branch today. Were those PRs improved with tests? Or they are just fixing code style issues?

**Comment by tim-hoffman** [comment]
Many of those PRs just make minor changes such as reformatting code, adding missing Override annotations, replacing StringBuffer with StringBuilder, adding generics to old code, and other such minor improvements. I am also pushing a few that add features which have been discussed (either in the PR or in the related issue) or fix bugs that I have found. I have not added test cases for any of these to the Soot test suite. I may have some test cases sitting around in my own project but it would take me some time to find and correlate them to the proper PRs.

**Comment by linghuiluo** [comment]
@tim-hoffman Merging those PRs with minor style changes is completely fine. Thanks for your contribution! Writing tests do require some extra time, however, it is better to do so next time such that the PRs can be reviewed and discussed. New features should not introduce bugs. Due to the lack of tests, we saw issues that claimed newly introduced changes broke integration tests of analyses built on top of soot. e.g. https://github.com/soot-oss/soot/issues/1614#issuecomment-853267363

**Pull request merged**
