### PR TITLE
Improve .NET import support

### PR DESCRIPTION
**Pull request by MarcMil**
This implementation takes supports rewriting of delegates and by-reference parameters and fixes a lot of bugs with the existing implementation.

### CODE REVIEW

**Comment by runner02** [comment]
Is it aligned with soot-dotnet project? 
The protobufs have changed

**Comment by StevenArzt** [comment]
We are currently actively working on improving the .net support and making it realiably usable. We will make a propre version of the ``soot-dotnet`` project available once this has matured sufficiently.

**Comment by runner02** [comment]
@StevenArzt Thanks for the prompt response.
Do you have any time estimation on this?

**Comment by StevenArzt** [comment]
Soon 😄

**Comment by runner02** [comment]
Thank you!

**Pull request merged**
