### PR TITLE
Fix jdoc and options deployment

### PR DESCRIPTION
**Pull request by mbenz89**

### CODE REVIEW

**Comment by mbenz89** [comment]
@anddann This removes the unnecessary build stuff for testing. It works...unfortunately, though, the complete content of the gh-page is overwritten and only the folder with the name of the current version remains. I've reverted the commits to gh-pages to get back to a proper state.

**Comment by mbenz89** [comment]
Also the index.htm file did not properly render.

**Comment by mbenz89** [comment]
Ok deployment now properly works: https://soot-oss.github.io/soot/docs/ and https://github.com/soot-oss/soot/tree/gh-pages/docs

The index file seems not to be enough to traverse the directory tree, though: https://soot-oss.github.io/soot/docs/docs/4.3.0-SNAPSHOT

**Comment by anddann** [comment]
Okay, thx I'll take a look w.r.t the folder issue

**Comment by anddann** [comment]
Thanks for your feedback. I finally adapted the index.html and ci pipeline file to create a correct overview of documentations

**Comment by anddann** [comment]
okay, the deployment works @mbenz89 .

However, it is also triggered for this PR? Is this intended?

**Comment by mbenz89** [comment]
@anddann Great!

> okay, the deployment works @mbenz89 .

However, it is also triggered for this PR? Is this intended?

Yes, that is intended to be able to properly test this! I will care about reverting the ci file properly and adapting the Readme.md

**Comment by anddann** [comment]
Super, thank you

**Pull request merged**
