### PR TITLE
Add support for more Android AsyncTask functions for callgraph

### PR DESCRIPTION
**Pull request by flankerhqd**
Add support for more Android AsyncTask functions in virtualedges.xml.
Add mock tests.
Fix MethodNodeFactory to handle situation where function parameter difference may lead to NPE or OOB Exception.

### CODE REVIEW

**Comment by flankerhqd** [comment]
Enhancement for https://github.com/secure-software-engineering/FlowDroid/issues/335

**Comment by linghuiluo** [comment]
@flankerhqd Can you fix the failed Soot CI / Check style´and license conformity (pull_request)

**Comment by StevenArzt** [comment]
@flankerhqd Can you please have a look at the failed stylecheck and update your PR accordingly?

**Comment by flankerhqd** [comment]
Sure, working on it.

**Comment by flankerhqd** [comment]
Done. 

BTW: are the signature statements in https://github.com/soot-oss/soot/blob/3966f565db6dc2882c3538ffc39e44f4c14b5bcf/src/main/java/soot/jimple/toolkits/callgraph/OnFlyCallGraphBuilder.java#L234 useful anymore? I don't see any reference to them.

**Pull request merged**
